# Generated by Django 4.2.6 on 2023-11-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('ip', models.CharField(max_length=100)),
                ('shipping', models.IntegerField()),
                ('cartTotal', models.IntegerField()),
                ('cartItems', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
