# Generated by Django 4.2.6 on 2023-11-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="default.png", upload_to="images/"),
        ),
    ]
